/**
 * Deployment-package static server (Task 23 I).
 *
 * `renderServerMjs()` emits a SELF-CONTAINED `server.mjs` (node:http +
 * node:fs only — no node_modules, no framework) that serves the exported
 * `site/` directory next to it. It exists so the package runs anywhere a
 * Node >= 18 binary exists; any static file host (nginx, S3+CDN, GitHub
 * Pages...) can serve the same directory with equivalent rules:
 *
 *   /path            → site/path.html (Next static export, trailingSlash:false)
 *   /path/           → 308 redirect to /path
 *   unknown path     → 404 with site/404.html
 *   /_next/static/*, /media/*  → immutable cache (content-hashed names)
 *
 * The smoke suite spawns the emitted file against a fixture site and asserts
 * these behaviors over real HTTP.
 */

export const SERVER_READY_PREFIX = "wr-production-server listening on ";

export function renderServerMjs(): string {
  return `#!/usr/bin/env node
/**
 * web-recon production package server — generated by the production compiler.
 * Self-contained: node:http + node:fs only. Serves ./site next to this file.
 *
 *   node server.mjs [--port N] [--host H]     (defaults: PORT env or 3000, 127.0.0.1)
 */
import { createServer } from "node:http";
import { createReadStream, existsSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SITE_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "site");

const args = process.argv.slice(2);
function argValue(name, fallback) {
  const index = args.indexOf(name);
  return index !== -1 && index + 1 < args.length ? args[index + 1] : fallback;
}
const port = Number(argValue("--port", process.env.PORT ?? "3000"));
const host = argValue("--host", "127.0.0.1");

const CONTENT_TYPES = {
  html: "text/html; charset=utf-8",
  txt: "text/plain; charset=utf-8",
  css: "text/css; charset=utf-8",
  js: "text/javascript; charset=utf-8",
  mjs: "text/javascript; charset=utf-8",
  json: "application/json; charset=utf-8",
  xml: "application/xml; charset=utf-8",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  webp: "image/webp",
  gif: "image/gif",
  avif: "image/avif",
  svg: "image/svg+xml",
  ico: "image/x-icon",
  woff2: "font/woff2",
  woff: "font/woff",
  ttf: "font/ttf",
  otf: "font/otf",
  mp4: "video/mp4",
  webm: "video/webm",
  map: "application/json",
};

function contentType(filePath) {
  const ext = filePath.split(".").pop()?.toLowerCase() ?? "";
  return CONTENT_TYPES[ext] ?? "application/octet-stream";
}

function cacheControl(urlPath) {
  if (urlPath.startsWith("/_next/static/") || urlPath.startsWith("/media/")) {
    return "public, max-age=31536000, immutable";
  }
  return "no-cache";
}

/** Resolve a request path to a file inside SITE_DIR, or null. */
function resolveFile(urlPath) {
  let pathname;
  try {
    pathname = decodeURIComponent(urlPath.split("?")[0].split("#")[0]);
  } catch {
    return null;
  }
  if (pathname.includes("\\0")) return null;
  const normalized = path.posix.normalize(pathname);
  if (!normalized.startsWith("/") || normalized.includes("..")) return null;
  const candidates =
    normalized === "/"
      ? ["index.html"]
      : [normalized.slice(1), normalized.slice(1) + ".html", normalized.slice(1) + "/index.html"];
  for (const candidate of candidates) {
    const filePath = path.join(SITE_DIR, candidate);
    if (!filePath.startsWith(SITE_DIR + path.sep) && filePath !== path.join(SITE_DIR, "index.html")) continue;
    if (existsSync(filePath) && statSync(filePath).isFile()) return filePath;
  }
  return null;
}

const server = createServer((request, response) => {
  const method = request.method ?? "GET";
  if (method !== "GET" && method !== "HEAD") {
    response.writeHead(405, { allow: "GET, HEAD", "content-type": "text/plain" });
    response.end("method not allowed\\n");
    return;
  }
  const rawPath = (request.url ?? "/").split("?")[0];
  if (rawPath.length > 1 && rawPath.endsWith("/")) {
    response.writeHead(308, { location: rawPath.replace(/\\/+$/, "") || "/" });
    response.end();
    return;
  }
  const filePath = resolveFile(rawPath);
  if (filePath === null) {
    const notFoundFile = path.join(SITE_DIR, "404.html");
    if (existsSync(notFoundFile)) {
      response.writeHead(404, { "content-type": "text/html; charset=utf-8" });
      if (method === "HEAD") { response.end(); return; }
      createReadStream(notFoundFile).pipe(response);
    } else {
      response.writeHead(404, { "content-type": "text/plain" });
      response.end("not found\\n");
    }
    return;
  }
  const size = statSync(filePath).size;
  response.writeHead(200, {
    "content-type": contentType(filePath),
    "content-length": String(size),
    "cache-control": cacheControl(rawPath),
  });
  if (method === "HEAD") { response.end(); return; }
  createReadStream(filePath).pipe(response);
});

server.listen(port, host, () => {
  const address = server.address();
  const actualPort = typeof address === "object" && address !== null ? address.port : port;
  console.log("${SERVER_READY_PREFIX}http://" + host + ":" + actualPort);
});
`;
}
