import type {
  ElementSpecNode,
  SpecNode,
  TextSpecNode,
} from "../sitespec/index.js";
import { AssetResolver, annotateSvgRoot } from "./asset-resolver.js";
import {
  BUTTON_LIKE_INPUT_TYPES,
  SKIPPED_TAGS,
  VOID_ELEMENTS,
  adaptAttribute,
  hiddenStateAnnotation,
  isBooleanAttributePresent,
  isContentEditableEnabled,
} from "./react-attributes.js";
import type { LinkRewriter } from "./link-rewriter.js";
import {
  bindingKey,
  bindingProps,
  unknownProps,
  type InteractionPlan,
} from "./interaction-bindings.js";
import type { CorrectionPlan } from "./qa-corrections.js";
import { generatedDomId, rewriteRelations } from "./relations.js";
import {
  documentRootClassName,
  styleClassName,
  textBoxHeightRelievable,
  textBoxWidthRelievable,
  TEXT_BOX_HEIGHT_VARIANT_CLASS,
  TEXT_BOX_SHRINK_VARIANT_CLASS,
} from "./style-generator.js";
import type { PseudoRuleInput } from "./pseudo-generator.js";
import {
  ReconstructionError,
  type ReconstructionLimitationCode,
  type RuntimeElementNode,
  type RuntimeNode,
  type RuntimePropValue,
} from "./types.js";

/**
 * SiteSpec node → runtime node (items 54–60, 117, 118).
 *
 * A generic renderer, on purpose. `tagName` is emitted as it was observed and
 * handed to `React.createElement`; there is no map from `<mdn-dropdown>` to a
 * component, no "this looks like a card" rule, no flattening to `<div>`
 * (items 54, 117). MDN's custom elements, `<details>`, `<table>` and `<select>`
 * all survive as themselves, because the structure IS part of what was observed.
 *
 * Child ORDER is `childNodeIds` order, unchanged (item 60). Task 13 spent an
 * entire alignment pass recovering that `<p>Hello <strong>world</strong> !</p>`
 * is text-element-text; re-deriving it here would be re-litigating a solved
 * problem, and getting it wrong would be invisible in a screenshot diff.
 *
 * Text is the raw parsed value — never trimmed, never whitespace-collapsed
 * (item 59). `<pre>` and inline `</a> <a>` spacing are both destroyed by a
 * `trim()` that looks harmless.
 */

export interface CompileNodeContext {
  pageId: string;
  pageUrl: string;
  viewportId: "desktop" | "mobile";
  nodeById: ReadonlyMap<string, SpecNode>;
  generatedIdNodes: ReadonlySet<string>;
  assets: AssetResolver;
  links: LinkRewriter;
  interactions: InteractionPlan;
  /**
   * Does this style token produce a CSS rule? (Task 16.)
   *
   * A token whose computed style is empty — a `<video><source>`, which Chromium
   * never lays out — yields no rule, so a `className` pointing at it would be
   * dangling. Both sides ask the same question through
   * `hasRenderableDeclarations()`, so they cannot disagree.
   */
  styleRenders: (styleTokenId: string, documentRoot?: boolean) => boolean;
  /**
   * TASK 28.8 A3 — the token's COMPUTED properties, for the text-box relief
   * variants. Needed here and not only in the stylesheet writer because the
   * class goes on the element only when the token really carries the frozen
   * length the variant restates, so class and rule cannot disagree.
   *
   * OPTIONAL: with it absent no variant class is ever added and the compiled
   * tree is byte-identical to the pre-28.8 one.
   */
  styleLookup?: (styleTokenId: string) => Readonly<Record<string, string>> | undefined;
  /**
   * Task 15 corrections, present ONLY when a correction set was supplied. With
   * no corrections this field is undefined and every branch below is skipped, so
   * the generated bytes are identical to the Task 14 baseline (item 114).
   */
  corrections?: CorrectionPlan;
}

export interface CompileCounters {
  elementNodes: number;
  textNodes: number;
  styledNodes: number;
  generatedDomIds: number;
  rewrittenIdrefTokens: number;
  unresolvedIdrefTokens: number;
  elementAssetsRequested: number;
  resolvedImageSrc: number;
  resolvedSrcset: number;
  inlineSvgRendered: number;
  unresolvedElementAssets: number;
  droppedSrcsetCandidates: number;
  remoteAssetUrls: number;
  internalLinksRewritten: number;
  unresolvedInternalLinks: number;
  externalLinks: number;
  skippedSourceNodes: number;
  /** Nodes that carried an observed `scrollState` (Task 16, A2). */
  scrollStateNodes: number;
  /** …of those, how many got a `data-wr-scroll-*` for the runtime to restore. */
  scrollRestoreNodes: number;
  /** Parser-unstable edges expressed through an interposed container. */
  nestingAdaptations: number;
  /** TASK 28.8 FAST — nested interactive elements demoted to a layout-neutral tag. */
  nestingDemotions: number;
  usedStyleTokens: Set<string>;
  /**
   * TASK 28.8 A3 — the tokens that need a text-box relief variant rule, and the
   * NODES that carry each variant class. The stylesheet writer emits one rule
   * per token; the manifest reports the nodes, because that is the population
   * the defect was measured over.
   */
  textBoxHeightTokens: Set<string>;
  textBoxShrinkTokens: Set<string>;
  textBoxHeightNodes: number;
  textBoxShrinkNodes: number;
  pseudoRules: PseudoRuleInput[];
  limitations: Set<ReconstructionLimitationCode>;
}

export function newCounters(): CompileCounters {
  return {
    elementNodes: 0,
    textNodes: 0,
    styledNodes: 0,
    generatedDomIds: 0,
    rewrittenIdrefTokens: 0,
    unresolvedIdrefTokens: 0,
    elementAssetsRequested: 0,
    resolvedImageSrc: 0,
    resolvedSrcset: 0,
    inlineSvgRendered: 0,
    unresolvedElementAssets: 0,
    droppedSrcsetCandidates: 0,
    remoteAssetUrls: 0,
    internalLinksRewritten: 0,
    unresolvedInternalLinks: 0,
    externalLinks: 0,
    skippedSourceNodes: 0,
    scrollStateNodes: 0,
    scrollRestoreNodes: 0,
    nestingAdaptations: 0,
    nestingDemotions: 0,
    usedStyleTokens: new Set(),
    textBoxHeightTokens: new Set(),
    textBoxShrinkTokens: new Set(),
    textBoxHeightNodes: 0,
    textBoxShrinkNodes: 0,
    pseudoRules: [],
    limitations: new Set(),
  };
}

/** `<option>`'s value per HTML semantics: the attribute, else its text (item 46). */
export function optionValue(
  option: ElementSpecNode,
  nodeById: ReadonlyMap<string, SpecNode>,
): string {
  const declared = option.attributes["value"];
  if (declared !== undefined) return declared;
  return collectText(option, nodeById).replace(/[\t\n\f\r ]+/g, " ").trim();
}

/** Descendant text content, raw and in document order. */
export function collectText(
  node: ElementSpecNode,
  nodeById: ReadonlyMap<string, SpecNode>,
): string {
  let out = "";
  const walk = (id: string): void => {
    const child = nodeById.get(id);
    if (!child) return;
    if (child.type === "text") {
      out += child.value;
      return;
    }
    for (const grandchild of child.childNodeIds) walk(grandchild);
  };
  for (const id of node.childNodeIds) walk(id);
  return out;
}

/** Every `<option>` under a `<select>`, in document order (optgroups included). */
function selectOptions(
  select: ElementSpecNode,
  nodeById: ReadonlyMap<string, SpecNode>,
): ElementSpecNode[] {
  const out: ElementSpecNode[] = [];
  const walk = (id: string): void => {
    const child = nodeById.get(id);
    if (!child || child.type !== "element") return;
    if (child.tagName === "option") out.push(child);
    for (const grandchild of child.childNodeIds) walk(grandchild);
  };
  for (const id of select.childNodeIds) walk(id);
  return out;
}

/**
 * `<select>`'s initial selection, expressed the way React needs it (item 45).
 *
 * React owns a `<select>`'s selection through the PARENT, so putting `selected`
 * on the options — which is what the HTML said — produces a console warning and
 * a select React will fight with. `defaultValue` on the select says the same
 * thing in React's vocabulary, and an uncontrolled select keeps working.
 */
export function selectDefaultValue(
  select: ElementSpecNode,
  nodeById: ReadonlyMap<string, SpecNode>,
): { value?: RuntimePropValue } {
  const multiple = select.attributes["multiple"] !== undefined;
  const options = selectOptions(select, nodeById);
  const selected = options.filter(
    (option) =>
      option.attributes["selected"] !== undefined &&
      isBooleanAttributePresent("selected", option.attributes["selected"]!),
  );
  if (selected.length === 0) {
    // No `selected` in the source means the browser's own default applies, and
    // saying nothing reproduces it exactly. Inventing `defaultValue = first
    // option` would look identical here and be wrong the moment the source has
    // a `<select>` whose first option is disabled.
    return multiple ? { value: [] } : {};
  }
  if (multiple) {
    return { value: selected.map((option) => optionValue(option, nodeById)) };
  }
  // A non-multiple select honors the LAST `selected` option, per HTML parsing.
  return { value: optionValue(selected[selected.length - 1]!, nodeById) };
}

/** Compile one subtree. Returns `null` for nodes that are not rendered. */
export function compileNode(
  nodeId: string,
  context: CompileNodeContext,
  counters: CompileCounters,
): RuntimeNode | null {
  const node = context.nodeById.get(nodeId);
  if (!node) {
    throw new ReconstructionError(
      `${context.pageId}/${context.viewportId}: child node ${nodeId} is referenced but absent from the viewport tree`,
    );
  }
  if (node.type === "text") {
    counters.textNodes++;
    return { k: "t", v: node.value };
  }
  return compileElement(node, context, counters);
}

/*
 * ---------------------------------------------------------------------------
 * TASK 28.8 A3 — WHICH BOXES GET TEXT-BOX BLOCK-SIZE RELIEF.
 * ---------------------------------------------------------------------------
 *
 * Both predicates are pure functions of the SiteSpec tree — the child ids, the
 * tag names, and the token's computed values. Nothing here reads a URL, a
 * hostname or a site-specific hint; the same box on any site gets the same
 * answer. See `style-generator.ts` for the defect these relieve and for why the
 * relief is a variant class rather than a change to the shared token.
 */

/** Elements whose box is the REPLACED content's, not a text measurement. */
const TEXT_BOX_REPLACED_TAGS: ReadonlySet<string> = new Set([
  "img",
  "svg",
  "video",
  "canvas",
  "iframe",
  "picture",
  "object",
  "embed",
  "input",
  "select",
  "textarea",
]);

/** Displays for which a `height` is not a block-size a reflow can grow. */
const TEXT_BOX_NON_BLOCK_DISPLAYS: ReadonlySet<string> = new Set([
  "inline",
  "none",
  "contents",
]);

/** Displays whose own width is shrink-to-fit. */
const TEXT_BOX_SHRINK_DISPLAYS: ReadonlySet<string> = new Set([
  "inline-block",
  "list-item",
  "table-cell",
  "inline-flex",
  "inline-grid",
]);

/** Parent displays that make a child's width shrink-to-fit (a flex/grid item). */
const TEXT_BOX_SHRINK_PARENT_DISPLAYS: ReadonlySet<string> = new Set([
  "flex",
  "inline-flex",
  "grid",
  "inline-grid",
]);

/**
 * Memoised per node INDEX, so a 1,600-node page walks its subtrees once and not
 * once per ancestor. The map is the identity of a page × viewport tree, which is
 * exactly the scope the answer is valid in.
 */
const TEXT_DESCENDANT_CACHE = new WeakMap<
  ReadonlyMap<string, SpecNode>,
  Map<string, boolean>
>();

/** Does the subtree rooted here contain any non-whitespace text? */
export function hasTextDescendant(
  nodeId: string,
  nodeById: ReadonlyMap<string, SpecNode>,
): boolean {
  let cache = TEXT_DESCENDANT_CACHE.get(nodeById);
  if (cache === undefined) {
    cache = new Map<string, boolean>();
    TEXT_DESCENDANT_CACHE.set(nodeById, cache);
  }
  const hit = cache.get(nodeId);
  if (hit !== undefined) return hit;
  const node = nodeById.get(nodeId);
  if (node === undefined) {
    cache.set(nodeId, false);
    return false;
  }
  if (node.type === "text") {
    const answer = node.value.trim() !== "";
    cache.set(nodeId, answer);
    return answer;
  }
  // Set BEFORE recursing so a malformed tree with a cycle terminates.
  cache.set(nodeId, false);
  let answer = false;
  for (const childId of node.childNodeIds) {
    if (hasTextDescendant(childId, nodeById)) {
      answer = true;
      break;
    }
  }
  cache.set(nodeId, answer);
  return answer;
}

/** Does this element have a DIRECT text child with non-whitespace content? */
function hasDirectText(
  node: ElementSpecNode,
  nodeById: ReadonlyMap<string, SpecNode>,
): boolean {
  for (const childId of node.childNodeIds) {
    const child = nodeById.get(childId);
    if (child?.type === "text" && child.value.trim() !== "") return true;
  }
  return false;
}

/**
 * `wr-tx` — the frozen `height` is a one-font text measurement, and the box does
 * not clip, so restating it as a FLOOR cannot change the truth-width render and
 * can only stop an overprint at every other width.
 *
 * The `overflow` gate is what keeps this honest: a box the source deliberately
 * made SHORTER than its content (`overflow: hidden` on a clamped card, a
 * carousel viewport) is expressing an intent, and growing it would be this
 * module overruling the source rather than repairing a measurement.
 */
export function textBoxHeightVariantApplies(
  node: ElementSpecNode,
  properties: Readonly<Record<string, string>> | undefined,
  nodeById: ReadonlyMap<string, SpecNode>,
): boolean {
  if (properties === undefined) return false;
  if (TEXT_BOX_REPLACED_TAGS.has(node.tagName)) return false;
  const display = properties["display"];
  if (display === undefined || TEXT_BOX_NON_BLOCK_DISPLAYS.has(display)) return false;
  const position = properties["position"];
  if (position === "absolute" || position === "fixed") return false;
  const overflow = properties["overflow"];
  const overflowY = properties["overflow-y"];
  if (overflow !== undefined && overflow !== "visible") return false;
  if (overflowY !== undefined && overflowY !== "visible") return false;
  return hasTextDescendant(node.nodeId, nodeById);
}

/**
 * `wr-sf` — the frozen `width` is a shrink-to-fit text measurement, so `auto`
 * re-derives it from the text in whatever font actually loaded.
 *
 * Restricted to boxes with DIRECT text, because that is the population whose
 * width the text determines. A shrink-to-fit box whose children are elements
 * gets its width from those children's own frozen boxes, and dropping its width
 * would change nothing while risking a flex/grid basis it did not need to.
 */
export function textBoxShrinkVariantApplies(
  node: ElementSpecNode,
  properties: Readonly<Record<string, string>> | undefined,
  parentProperties: Readonly<Record<string, string>> | undefined,
  nodeById: ReadonlyMap<string, SpecNode>,
): boolean {
  if (properties === undefined) return false;
  if (TEXT_BOX_REPLACED_TAGS.has(node.tagName)) return false;
  const position = properties["position"];
  if (position === "absolute" || position === "fixed") return false;
  const display = properties["display"];
  if (display === undefined || TEXT_BOX_NON_BLOCK_DISPLAYS.has(display)) return false;
  if (!hasDirectText(node, nodeById)) return false;
  if (TEXT_BOX_SHRINK_DISPLAYS.has(display)) return true;
  const float = properties["float"];
  if (float !== undefined && float !== "none") return true;
  const parentDisplay = parentProperties?.["display"];
  return parentDisplay !== undefined && TEXT_BOX_SHRINK_PARENT_DISPLAYS.has(parentDisplay);
}

function compileElement(
  node: ElementSpecNode,
  context: CompileNodeContext,
  counters: CompileCounters,
): RuntimeElementNode | null {
  const tagName = node.tagName;
  if (SKIPPED_TAGS.has(tagName)) {
    counters.skippedSourceNodes++;
    return null;
  }

  counters.elementNodes++;
  const props: Record<string, RuntimePropValue> = {};

  // --- identity -------------------------------------------------------------
  props["data-wr-node"] = node.nodeId;
  const hasGeneratedId = context.generatedIdNodes.has(node.nodeId);
  if (hasGeneratedId) {
    props["id"] = generatedDomId(context.pageId, context.viewportId, node.nodeId);
    counters.generatedDomIds++;
  }

  // --- style ----------------------------------------------------------------
  // An empty computed style is a real observation (a `<video><source>` never
  // enters layout), and a class with no rule behind it is not. Both are handled
  // by asking the generator whether this token renders at all.
  if (node.styleTokenId && context.styleRenders(node.styleTokenId)) {
    const tokenId = node.styleTokenId;
    const classes = [styleClassName(tokenId)];
    counters.usedStyleTokens.add(tokenId);
    counters.styledNodes++;
    /*
     * TASK 28.8 A3 — the text-box relief variants. The class goes on only when
     * the token really carries the frozen px length the variant restates, so
     * `.wr-stNNN.wr-tx` exists in the stylesheet exactly when some node wears
     * `wr-tx` — no dangling class, and `validateGeneratedApp` still checks it.
     */
    const lookup = context.styleLookup;
    if (lookup !== undefined) {
      const properties = lookup(tokenId);
      if (
        textBoxHeightRelievable(properties) &&
        textBoxHeightVariantApplies(node, properties, context.nodeById)
      ) {
        classes.push(TEXT_BOX_HEIGHT_VARIANT_CLASS);
        counters.textBoxHeightTokens.add(tokenId);
        counters.textBoxHeightNodes++;
      }
      const parent =
        node.parentNodeId !== undefined ? context.nodeById.get(node.parentNodeId) : undefined;
      const parentProperties =
        parent?.type === "element" && parent.styleTokenId !== undefined
          ? lookup(parent.styleTokenId)
          : undefined;
      if (
        textBoxWidthRelievable(properties) &&
        textBoxShrinkVariantApplies(node, properties, parentProperties, context.nodeById)
      ) {
        classes.push(TEXT_BOX_SHRINK_VARIANT_CLASS);
        counters.textBoxShrinkTokens.add(tokenId);
        counters.textBoxShrinkNodes++;
      }
    }
    props["className"] = classes.join(" ");
  }
  if (node.pseudo?.before) {
    counters.pseudoRules.push({
      pageId: context.pageId,
      viewportId: context.viewportId,
      nodeId: node.nodeId,
      which: "before",
      styleTokenId: node.pseudo.before.styleTokenId,
      ...(node.pseudo.before.content !== undefined
        ? { content: node.pseudo.before.content }
        : {}),
    });
  }
  if (node.pseudo?.after) {
    counters.pseudoRules.push({
      pageId: context.pageId,
      viewportId: context.viewportId,
      nodeId: node.nodeId,
      which: "after",
      styleTokenId: node.pseudo.after.styleTokenId,
      ...(node.pseudo.after.content !== undefined
        ? { content: node.pseudo.after.content }
        : {}),
    });
  }

  // --- attributes -----------------------------------------------------------
  const inputType = node.attributes["type"]?.toLowerCase();
  for (const [name, value] of Object.entries(node.attributes)) {
    if (name === "href") continue; // handled below, after link rewriting
    const adapted = adaptAttribute(tagName, name, value);
    if (adapted === null) continue;
    props[adapted.prop] = adapted.value;
    if (name === "hidden") {
      const enumerated = hiddenStateAnnotation(value);
      if (enumerated !== undefined) props["data-wr-hidden"] = enumerated;
    }
  }

  // --- form state (items 44, 45, 47, 48) ------------------------------------
  if (tagName === "input") {
    const checked = node.attributes["checked"];
    if (checked !== undefined && isBooleanAttributePresent("checked", checked)) {
      props["defaultChecked"] = true;
    }
    const value = node.attributes["value"];
    if (value !== undefined) {
      // `defaultValue` for every input type, including the button-like ones.
      // React renders it back out as the `value` ATTRIBUTE, so a submit button
      // keeps its label and its attribute semantics, and no input becomes a
      // controlled field without an onChange (items 44, 47).
      props["defaultValue"] = value;
      void BUTTON_LIKE_INPUT_TYPES;
    }
  } else if (tagName === "textarea") {
    const declared = node.attributes["value"];
    const text = collectText(node, context.nodeById);
    const initial = declared !== undefined ? declared : text;
    if (initial !== "") props["defaultValue"] = initial;
  } else if (tagName === "select") {
    const { value } = selectDefaultValue(node, context.nodeById);
    if (value !== undefined) props["defaultValue"] = value;
  }

  if (
    node.attributes["contenteditable"] !== undefined &&
    isContentEditableEnabled(node.attributes["contenteditable"]!) &&
    node.childNodeIds.length > 0
  ) {
    // A React renderer adaptation, not a source fact: React warns when a
    // contentEditable element has children it does not control (item 49).
    props["suppressContentEditableWarning"] = true;
  }

  // --- relations (items 35–38) ---------------------------------------------
  for (const rewrite of rewriteRelations(node, {
    pageId: context.pageId,
    viewportId: context.viewportId,
    hasGeneratedId: (id) => context.generatedIdNodes.has(id),
  })) {
    counters.rewrittenIdrefTokens += rewrite.resolvedTokens;
    counters.unresolvedIdrefTokens += rewrite.unresolvedTokens;
    const adapted = adaptAttribute(tagName, rewrite.attribute, rewrite.value);
    if (adapted) props[adapted.prop] = adapted.value;
  }

  // --- links (items 81–83) --------------------------------------------------
  // A resolved `#fragment` has already been rewritten above by the relation
  // pass; anything still unhandled reaches the rewriter, and a bare `#` (which
  // Task 13 does not turn into a relation) is passed through rather than lost.
  const href = node.attributes["href"];
  if (href !== undefined && props["href"] === undefined) {
    if (href.startsWith("#")) {
      props["href"] = href;
    } else {
      const rewritten = context.links.rewrite(href, context.pageUrl);
      props["href"] = rewritten.href;
      if (rewritten.kind === "internal-route") counters.internalLinksRewritten++;
      else if (rewritten.kind === "internal-unresolved") {
        counters.unresolvedInternalLinks++;
        counters.limitations.add("internal-link-not-in-route-table");
      } else if (rewritten.kind === "external") counters.externalLinks++;
    }
  }

  // --- assets (items 69–79) -------------------------------------------------
  let inlineSvg: string | undefined;
  // Task 28.5B: a `<video>` is added here alongside `img`/`svg` even when it
  // carries zero assetRefs, because AssetResolver.resolve() cannot see the
  // one signal that decides whether that emptiness is innocent — sibling
  // `<source>` children. `videoMediaMissingAndNoSourceChild` below is that
  // signal, computed here where the node tree is available.
  //
  // 28.5B correction (GAP-A): `source` joins them for the same reason in
  // mirror image — a `<source>` with zero assetRefs lost its media and used
  // to be skipped here entirely, which (together with the parent `<video>`
  // being judged innocent *because* a `<source>` child existed) let a missing
  // video coexist with `unresolvedElementAssets = 0`.
  if (
    node.assetRefs.length > 0 ||
    tagName === "img" ||
    tagName === "svg" ||
    tagName === "video" ||
    tagName === "source"
  ) {
    counters.elementAssetsRequested++;
    const resolved = context.assets.resolve(tagName, node.assetRefs);
    counters.remoteAssetUrls += resolved.remoteUrls;
    counters.droppedSrcsetCandidates += resolved.droppedSrcsetCandidates;
    if (resolved.droppedSrcsetCandidates > 0) {
      counters.limitations.add("srcset-candidate-descriptor-missing");
    }
    if (resolved.src !== undefined) {
      props["src"] = resolved.src;
      counters.resolvedImageSrc++;
    }
    if (resolved.srcSet !== undefined) {
      props["srcSet"] = resolved.srcSet;
      counters.resolvedSrcset++;
    }
    if (resolved.inlineSvg !== undefined) {
      inlineSvg = resolved.inlineSvg;
      counters.inlineSvgRendered++;
    }
    /**
     * A `<video>` carrying no media asset of its OWN is only innocent when a
     * `<source>` child can supply the media (the standard `<video><source
     * .../></video>` pattern — Task 28.5B item 4). With neither its own media
     * NOR a source child, its content silently disappeared and the resolver
     * flags nothing, because it cannot see children. This is that missing
     * case, wired here instead of widening AssetResolver's contract.
     *
     * 28.5B correction (GAP-B): the trigger is `resolved.noOwnMediaAsset`, not
     * `node.assetRefs.length === 0`. The old test was asymmetric — a `<video>`
     * carrying only the `background-image` ref that collect-assets.ts pushes
     * onto every styled element has `assetRefs.length > 0`, so it escaped this
     * guard *and* was flagged unresolved by the resolver, even with perfectly
     * good `<source>` children. Asking whether MEDIA arrived (asset-resolver.ts,
     * `MEDIA_ASSET_KINDS`) rather than whether any ref arrived makes the guard
     * symmetric and stops the false positive.
     *
     * Counting point (GAP-A): a broken `<source>` child is counted at the
     * CHILD, by the resolver's empty-assetRefs / no-src branches, never also at
     * this parent — one increment per element whose media is genuinely lost.
     * A `<video>` with a `<source>` child therefore never counts here, even
     * when that child is itself counted.
     */
    const videoMediaMissingAndNoSourceChild =
      tagName === "video" &&
      resolved.noOwnMediaAsset &&
      !node.childNodeIds.some((id) => {
        const child = context.nodeById.get(id);
        return child !== undefined && child.type === "element" && child.tagName === "source";
      });
    if (resolved.unresolved || videoMediaMissingAndNoSourceChild) {
      counters.unresolvedElementAssets++;
      counters.limitations.add("element-asset-unresolved");
    }
  }

  // --- observed scroll offset (Task 16, A2, items 17, 18) -------------------
  // `scrollTop` is a DOM PROPERTY, not a declarative attribute: React has no
  // prop for it and server-rendered HTML cannot express it. So the observation
  // travels as compact metadata on the element that needs it, and the generic
  // client runtime applies it once after hydration. Only elements at a NON-ZERO
  // offset carry anything — a scroller that was at the top needs no instruction,
  // and a clone starts every scroller at 0 anyway.
  if (node.scrollState) {
    const { scrollTop, scrollLeft } = node.scrollState;
    if (scrollTop !== 0) {
      props["data-wr-scroll-top"] = String(scrollTop);
      counters.scrollRestoreNodes++;
    }
    if (scrollLeft !== 0) {
      props["data-wr-scroll-left"] = String(scrollLeft);
      if (scrollTop === 0) counters.scrollRestoreNodes++;
    }
    counters.scrollStateNodes++;
  }

  // --- QA corrections (Task 15, items 105, 113) -----------------------------
  // Applied AFTER asset resolution so a recovered image overrides the absence of
  // a src rather than racing with it, and never when no correction set exists.
  if (context.corrections) {
    const correctionKey = bindingKey(context.pageId, context.viewportId, node.nodeId);
    const correctedSrc = context.corrections.imageSrc.get(correctionKey);
    if (correctedSrc !== undefined) props["src"] = correctedSrc;
    if (context.corrections.revealNodes.has(correctionKey)) props["data-wr-reveal"] = "1";
  }

  // --- interaction annotations (items 85, 89, 96, 105, 106) -----------------
  const key = bindingKey(context.pageId, context.viewportId, node.nodeId);
  const binding = context.interactions.bindings.get(key);
  if (binding) {
    for (const [name, value] of Object.entries(bindingProps(binding))) {
      props[name] = value;
    }
    if (binding.targetNodeId !== undefined) {
      props["data-wr-target-id"] = generatedDomId(
        context.pageId,
        context.viewportId,
        binding.targetNodeId,
      );
    }
    if (binding.dynamicTargetId !== undefined) {
      // The trigger's own aria-controls named a per-render source id that is not
      // in the clone. It has to name the region the CLONE will mount (item 96).
      props["aria-controls"] = binding.dynamicTargetId;
    }
  }
  const unknown = context.interactions.unknowns.get(key);
  if (unknown) {
    for (const [name, value] of Object.entries(unknownProps(unknown))) {
      props[name] = value;
    }
  }
  if (context.interactions.revealTargets.has(key)) {
    // This region's observed at-rest style hides it with CSS, so the runtime
    // needs a handle the style class cannot outrank (item 93).
    props["data-wr-reveal"] = "1";
  }

  // --- inline SVG (items 74–77) --------------------------------------------
  if (inlineSvg !== undefined) {
    const svgAttributes: Record<string, string> = {
      "data-wr-node": node.nodeId,
    };
    const className = props["className"];
    if (typeof className === "string") svgAttributes["class"] = className;
    const id = props["id"];
    if (typeof id === "string") svgAttributes["id"] = id;
    return {
      k: "e",
      n: node.nodeId,
      // The markup carries its own `<svg>` root, so the host element exists only
      // to hand React a container. `display: contents` keeps it out of layout.
      t: "span",
      p: { className: "wr-svg-host" },
      v: annotateSvgRoot(inlineSvg, svgAttributes),
    };
  }

  // --- children -------------------------------------------------------------
  const runtime: RuntimeElementNode = { k: "e", n: node.nodeId, t: tagName };
  if (Object.keys(props).length > 0) runtime.p = props;

  if (VOID_ELEMENTS.has(tagName)) {
    if (node.childNodeIds.length > 0) {
      throw new ReconstructionError(
        `${context.pageId}/${context.viewportId}: void element <${tagName}> (${node.nodeId}) ` +
          `has ${node.childNodeIds.length} child node(s); React cannot render children into it`,
      );
    }
    return runtime;
  }
  // `<textarea>`'s content became `defaultValue`; emitting both is a React
  // warning and a doubled value (item 48).
  if (tagName === "textarea") return runtime;

  const children: RuntimeNode[] = [];
  for (const childId of node.childNodeIds) {
    const child = compileNode(childId, context, counters);
    if (child !== null) children.push(child);
  }
  if (children.length > 0) runtime.c = children;
  return runtime;
}

/**
 * Compile the DOCUMENT ROOT of a viewport (item 56).
 *
 * A SiteSpec tree is rooted at `<html>` and holds a `<body>`; a Next.js page
 * renders INSIDE an `<html><body>` the framework owns, so re-emitting those two
 * tags would nest a document in a document. They become `div`s that keep
 * everything about their observed style except the document-box geometry, and
 * the adaptation is recorded rather than hidden.
 */
export function compileDocumentRoot(
  rootNodeIds: readonly string[],
  context: CompileNodeContext,
  counters: CompileCounters,
): { root: RuntimeElementNode; documentRootTokens: string[] } {
  const documentRootTokens: string[] = [];

  const adapt = (node: ElementSpecNode): RuntimeElementNode => {
    counters.elementNodes++;
    const props: Record<string, RuntimePropValue> = {
      "data-wr-node": node.nodeId,
      "data-wr-doc-tag": node.tagName,
    };
    // The document-root class also DROPS the document-box geometry, so a token
    // that is nothing but width/height renders nothing here even though it
    // renders elsewhere — hence the second argument.
    if (node.styleTokenId && context.styleRenders(node.styleTokenId, true)) {
      props["className"] = documentRootClassName(node.styleTokenId);
      documentRootTokens.push(node.styleTokenId);
      counters.styledNodes++;
    }
    for (const name of ["lang", "dir"]) {
      const value = node.attributes[name];
      if (value !== undefined) props[name] = value;
    }
    const children: RuntimeNode[] = [];
    for (const childId of node.childNodeIds) {
      const child = context.nodeById.get(childId);
      if (child && child.type === "element" && isDocumentRootTag(child.tagName)) {
        children.push(adapt(child));
        continue;
      }
      const compiled = compileNode(childId, context, counters);
      if (compiled !== null) children.push(compiled);
    }
    return { k: "e", n: node.nodeId, t: "div", p: props, ...(children.length > 0 ? { c: children } : {}) };
  };

  const roots: RuntimeNode[] = [];
  for (const id of rootNodeIds) {
    const node = context.nodeById.get(id);
    if (!node || node.type !== "element") continue;
    if (isDocumentRootTag(node.tagName)) {
      roots.push(adapt(node));
      continue;
    }
    const compiled = compileNode(id, context, counters);
    if (compiled !== null) roots.push(compiled);
  }

  if (roots.length === 1 && roots[0]!.k === "e") {
    return { root: roots[0] as RuntimeElementNode, documentRootTokens };
  }
  // More than one root is possible in the schema even though every observation
  // in the corpus has exactly one; wrapping keeps the runtime shape stable.
  return {
    root: {
      k: "e",
      n: "root",
      t: "div",
      p: { "data-wr-doc-tag": "virtual-root" },
      c: roots,
    },
    documentRootTokens,
  };
}

function isDocumentRootTag(tagName: string): boolean {
  return tagName === "html" || tagName === "body";
}

/** Text-node type guard used by the fixtures and validators. */
export function isTextSpecNode(node: SpecNode): node is TextSpecNode {
  return node.type === "text";
}
