import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { TemplateCompileError, TEMPLATE_DATA_DIR } from "./types.js";
import { SLOT_CONTENT_TS, TEMPLATE_LOAD_PAGE_TS } from "./app-templates.js";
import type { AssembledArtifacts } from "./assemble.js";

/**
 * Template app emission.
 *
 * The template app IS the Exact Reconstruction app — copied byte for byte —
 * plus the slot layer:
 *
 *   template-data/{slots,slot-bindings,default-content}.json   (the contract)
 *   src/runtime/slot-content.ts                                (the applier)
 *   src/runtime/load-page.ts                                   (one added call)
 *   package.json                                               (renamed)
 *
 * Nothing else is touched: the page data, route map, styles, interaction
 * runtime and every other generated file stay identical to the exact app, so
 * any observable difference between the two apps can only come from the slot
 * layer — which is exactly what the parity QA measures.
 *
 * The copy excludes `node_modules` and `.next` (build products, not artifact)
 * and `next-env.d.ts` (regenerated by `next build`).
 */

const COPY_EXCLUDES = new Set(["node_modules", ".next", "next-env.d.ts"]);

export interface GenerateTemplateAppOptions {
  /** The exact reconstruction's `app/` directory (read only). */
  sourceAppDir: string;
  /** The template run's `app/` directory (created). */
  targetAppDir: string;
  artifacts: AssembledArtifacts;
  /** `wr-template-<slug>` for the generated package.json. */
  packageName: string;
}

export interface GeneratedTemplateApp {
  copiedFromAppDir: string;
  templateDataFiles: string[];
  rewrittenFiles: string[];
}

export async function generateTemplateApp(
  options: GenerateTemplateAppOptions,
): Promise<GeneratedTemplateApp> {
  const { sourceAppDir, targetAppDir, artifacts } = options;

  await cp(sourceAppDir, targetAppDir, {
    recursive: true,
    filter: (source) => {
      const name = path.basename(source);
      return !COPY_EXCLUDES.has(name);
    },
  });

  // Drift guard: the loader this generator replaces must still be the loader
  // it was written against. If the reconstruction generator's load-page.ts
  // changes shape upstream, fail here instead of silently shipping a template
  // loader that diverges from the exact app in more than the one added call.
  const loadPageFile = path.join(targetAppDir, "src", "runtime", "load-page.ts");
  const originalLoadPage = await readFile(loadPageFile, "utf8");
  if (!originalLoadPage.includes("JSON.parse(raw) as RuntimePage")) {
    throw new TemplateCompileError(
      "the exact app's load-page.ts no longer matches the shape this template generator patches — " +
        "update src/recon-template/app-templates.ts against the current runtime template",
    );
  }

  const dataDir = path.join(targetAppDir, TEMPLATE_DATA_DIR);
  await mkdir(dataDir, { recursive: true });
  const templateDataFiles: string[] = [];
  const writeJson = async (name: string, value: unknown): Promise<void> => {
    const file = path.join(dataDir, name);
    await writeFile(file, JSON.stringify(value, null, 2) + "\n", "utf8");
    templateDataFiles.push(path.join(TEMPLATE_DATA_DIR, name));
  };
  await writeJson("slots.json", artifacts.slotsFile);
  await writeJson("slot-bindings.json", artifacts.bindingsFile);
  await writeJson("default-content.json", artifacts.defaultContentFile);

  await writeFile(
    path.join(targetAppDir, "src", "runtime", "slot-content.ts"),
    SLOT_CONTENT_TS,
    "utf8",
  );
  await writeFile(loadPageFile, TEMPLATE_LOAD_PAGE_TS, "utf8");

  const packageJsonFile = path.join(targetAppDir, "package.json");
  const packageJson = JSON.parse(await readFile(packageJsonFile, "utf8")) as Record<string, unknown>;
  packageJson.name = options.packageName;
  await writeFile(packageJsonFile, JSON.stringify(packageJson, null, 2) + "\n", "utf8");

  return {
    copiedFromAppDir: sourceAppDir,
    templateDataFiles,
    rewrittenFiles: ["src/runtime/load-page.ts", "src/runtime/slot-content.ts", "package.json"],
  };
}
