import { createHash } from "node:crypto";

/**
 * Deterministic reader for the template app's OWN generated stylesheet
 * (`app/public/wr/generated-styles.css`).
 *
 * That file is machine-generated by `style-generator.ts` / the pseudo and
 * target-state generators: exactly one rule per line, `selector{prop:value;…}`,
 * no @media blocks, no comments after the header line. This module does not
 * attempt to be a general CSS parser — it reads only that shape and refuses
 * anything else, because the stylesheet IS this pipeline's paint truth and a
 * hand-edited stylesheet would invalidate the extraction evidence.
 */

export type StylesheetSelectorKind = "style-token" | "doc-root" | "node-scoped";

export interface StylesheetRule {
  /** The selector exactly as written — the overlay reuses it verbatim. */
  selector: string;
  kind: StylesheetSelectorKind;
  /** For `style-token` / `doc-root` rules: the `st000123` token id. */
  styleTokenId?: string;
  /** True when the selector addresses a ::before/::after pseudo-element. */
  pseudo: boolean;
  /** True when the selector is gated on an open/revealed interaction state. */
  revealedState: boolean;
  declarations: Record<string, string>;
}

export interface ParsedStylesheet {
  rules: StylesheetRule[];
  ruleCount: number;
  sha256: string;
  byteLength: number;
}

const TOKEN_RULE = /^\.wr-(st\d+)$/;
const DOC_RULE = /^\.wr-doc-(st\d+)$/;

export function parseGeneratedStylesheet(css: string): ParsedStylesheet {
  const rules: StylesheetRule[] = [];
  // The pipeline's stylesheets mix two machine shapes — compact one-line
  // rules (style-generator) and pretty-printed blocks (pseudo/target-state
  // generators). Neither nests braces, uses @-rules, or allows `{};` inside
  // a value (isSafeCssValue upstream), so a flat brace scan is exact.
  const source = css.replace(/\/\*[\s\S]*?\*\//g, "");
  const RULE = /([^{}]+)\{([^{}]*)\}/g;
  let match: RegExpExecArray | null;
  while ((match = RULE.exec(source)) !== null) {
    const selector = match[1].trim().replace(/\s+/g, " ");
    if (selector === "") {
      throw new Error("generated stylesheet has a rule with an empty selector (unsupported shape)");
    }
    const declarations: Record<string, string> = {};
    for (const declaration of match[2].split(";")) {
      const trimmed = declaration.trim();
      if (trimmed === "") continue;
      const colon = trimmed.indexOf(":");
      if (colon <= 0) continue;
      declarations[trimmed.slice(0, colon).trim()] = trimmed.slice(colon + 1).trim();
    }
    const tokenMatch = TOKEN_RULE.exec(selector);
    const docMatch = DOC_RULE.exec(selector);
    const kind: StylesheetSelectorKind = tokenMatch
      ? "style-token"
      : docMatch
        ? "doc-root"
        : "node-scoped";
    rules.push({
      selector,
      kind,
      ...(tokenMatch ? { styleTokenId: tokenMatch[1] } : {}),
      ...(docMatch ? { styleTokenId: docMatch[1] } : {}),
      pseudo: /::(?:before|after)$/.test(selector),
      revealedState: selector.includes("[data-wr-revealed"),
      declarations,
    });
  }
  return {
    rules,
    ruleCount: rules.length,
    sha256: createHash("sha256").update(css).digest("hex"),
    byteLength: Buffer.byteLength(css, "utf8"),
  };
}

// ---------------------------------------------------------------------------
// Border shorthand decomposition
// ---------------------------------------------------------------------------

export interface BorderShorthand {
  /** `1px solid` — kept VERBATIM so the layout half can never change. */
  prefix: string;
  color: string;
  /** A border that cannot paint (0 width / style none) is not a paint occurrence. */
  paints: boolean;
}

/**
 * The Observer records computed borders as `<width> <style> <color>` (Chromium
 * shorthand serialization). The color is always the trailing component and may
 * contain spaces (`rgb(1, 2, 3)`), so split on the first color-ish token.
 */
export function parseBorderShorthand(value: string): BorderShorthand | undefined {
  const match = /^(\S+)\s+(\S+)\s+(.+)$/.exec(value.trim());
  if (!match) return undefined;
  const [, width, style, color] = match;
  return {
    prefix: `${width} ${style}`,
    color: color.trim(),
    paints: style !== "none" && style !== "hidden" && width !== "0px",
  };
}

// ---------------------------------------------------------------------------
// Paint value classification
// ---------------------------------------------------------------------------

/** rgba(…, 0) and the `transparent` keyword paint nothing. */
export function isTransparentColor(value: string): boolean {
  if (value === "transparent") return true;
  const match = /^rgba\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*,\s*([0-9.]+)\s*\)$/.exec(value);
  return match !== undefined && match !== null && Number.parseFloat(match[1]) === 0;
}

export interface ParsedColor {
  r: number;
  g: number;
  b: number;
  a: number;
}

/** Parses the color spellings this pipeline actually meets: rgb()/rgba()/#hex. */
export function parseColor(value: string): ParsedColor | undefined {
  const v = value.trim();
  let match = /^rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)$/.exec(v);
  if (match) return { r: +match[1], g: +match[2], b: +match[3], a: 1 };
  match = /^rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([0-9.]+)\s*\)$/.exec(v);
  if (match) return { r: +match[1], g: +match[2], b: +match[3], a: Number.parseFloat(match[4]) };
  match = /^#([0-9a-f]{6})$/i.exec(v);
  if (match) {
    const n = Number.parseInt(match[1], 16);
    return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255, a: 1 };
  }
  match = /^#([0-9a-f]{3})$/i.exec(v);
  if (match) {
    const [r, g, b] = match[1].split("").map((c) => Number.parseInt(c + c, 16));
    return { r, g, b, a: 1 };
  }
  if (v === "white") return { r: 255, g: 255, b: 255, a: 1 };
  if (v === "black") return { r: 0, g: 0, b: 0, a: 1 };
  return undefined;
}

function channel(v: number): number {
  const s = v / 255;
  return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
}

/** WCAG relative luminance (alpha ignored — callers gate on opacity first). */
export function relativeLuminance(color: ParsedColor): number {
  return 0.2126 * channel(color.r) + 0.7152 * channel(color.g) + 0.0722 * channel(color.b);
}

/** WCAG contrast ratio between two parsed colors. */
export function contrastRatio(a: ParsedColor, b: ParsedColor): number {
  const la = relativeLuminance(a);
  const lb = relativeLuminance(b);
  const [hi, lo] = la >= lb ? [la, lb] : [lb, la];
  return (hi + 0.05) / (lo + 0.05);
}

/** Saturation proxy: max−min channel distance (0 = grey). */
export function colorChroma(color: ParsedColor): number {
  return Math.max(color.r, color.g, color.b) - Math.min(color.r, color.g, color.b);
}
