import { lstat, readFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { AssetEntrySchema } from "../assets/assets";
import { RecordIdSchema, SlugSchema } from "../content/schema";
import { sha256 } from "../util/hash";

/**
 * The "managed portfolio" sidecar: data/sites/<siteId>/portfolio.managed.json.
 *
 * Present = the site's portfolio is GENERATED by `site:portfolio-sync` from the canonical data another
 * system owns (platform/portfolio-sync/contract.ts). It records exactly what the generator owns:
 *
 *   content[]  the two generated documents (content/projects.json, content/categories.json), by sha256
 *   assets[]   the generated image files under assets/ and the registry entries that name them
 *   retired[]  record id → the detail slug it was last served under, for every record that LEFT the
 *              generated portfolio: recorded the moment an id is no longer in the export (on the first
 *              managed run "before" is the hand-authored projects.json) or is named by
 *              changes.removing; kept until the same id is published again. The site loader reads it:
 *              a banner CTA to a retired id is "known but not served" (the CTA is hidden at render
 *              time, exactly like a draft), while an id that is neither stored nor retired is still a
 *              typo and fails the load.
 *
 * Everything else in the site directory — site.json, settings, slots, theme, banners, reviews, the
 * logo and every other registry entry — stays owned by the site and is never written by the generator.
 *
 * The sidecar is NOT part of the site snapshot: it adds nothing to siteSnapshotHash / buildInputId.
 * Absent = an ordinary hand-authored site; nothing in this module applies to it.
 */

export const MANAGED_FILE = "portfolio.managed.json";
export const MANAGED_SCHEMA = "managed-portfolio@1";
export const PROJECTS_PATH = "content/projects.json";
export const CATEGORIES_PATH = "content/categories.json";
export const REGISTRY_PATH = "assets/registry.json";
export const MANAGED_CONTENT_PATHS = [CATEGORIES_PATH, PROJECTS_PATH] as const;
/**
 * The TRACKED adoption marker: data/sites/<siteId>/portfolio.source.json. The sidecar above is produced
 * in the publisher's checkout and is not committed, so by itself it cannot tell ANOTHER checkout that
 * the committed content/projects.json is no longer the truth. The marker can: once a site is adopted
 * (the file is committed), every checkout refuses to load / build the site without a consistent
 * sidecar, and the manual site:publish refuses it. Like the sidecar it is outside the site snapshot.
 */
export const SOURCE_MARKER_FILE = "portfolio.source.json";
export const SOURCE_MARKER_SCHEMA = "portfolio-source@1";
export const SourceMarkerSchema = z.object({ schema: z.literal(SOURCE_MARKER_SCHEMA), managedBy: z.literal("boostchat") }).strict();
export const SOURCE_MARKER_TEXT = `${JSON.stringify({ schema: SOURCE_MARKER_SCHEMA, managedBy: "boostchat" }, null, 2)}\n`;

/** true = the site is adopted (its portfolio is owned by BoostChat). A malformed marker throws. */
export async function hasSourceMarker(siteDir: string): Promise<boolean> {
  let text: string;
  try {
    text = await readFile(path.join(siteDir, SOURCE_MARKER_FILE), "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw new ManagedPortfolioError(`cannot read ${SOURCE_MARKER_FILE}: ${(error as Error).message}`);
  }
  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch {
    throw new ManagedPortfolioError(`${SOURCE_MARKER_FILE} is not valid JSON`);
  }
  if (!SourceMarkerSchema.safeParse(raw).success) throw new ManagedPortfolioError(`${SOURCE_MARKER_FILE} invalid: expected ${SOURCE_MARKER_TEXT.replace(/\s+/g, " ").trim()}`);
  return true;
}

export const MANAGED_NOTICE =
  "GENERATED by site:portfolio-sync. Do not edit this file, the content files or the asset files it lists: change the portfolio in the BoostChat admin and publish it; the publisher regenerates them.";

const Sha256 = z.string().regex(/^[0-9a-f]{64}$/);

export const ManagedAssetSchema = AssetEntrySchema.extend({ sha256: Sha256, size: z.number().int().positive() }).strict();
export type ManagedAsset = z.infer<typeof ManagedAssetSchema>;

export const ManagedManifestSchema = z
  .object({
    schema: z.literal(MANAGED_SCHEMA),
    notice: z.string(),
    source: z.object({ schema: z.string().min(1), siteId: z.string().min(1), revision: z.number().int().nonnegative() }).strict(),
    content: z.array(z.object({ path: z.enum(MANAGED_CONTENT_PATHS), sha256: Sha256, size: z.number().int().nonnegative() }).strict()),
    assets: z.array(ManagedAssetSchema),
    retired: z.array(z.object({ id: RecordIdSchema, slug: SlugSchema }).strict()),
    /**
     * Present ONLY while a regeneration is being written: the generated files of the previous
     * generation that this one deletes. It is written first and dropped last, so a run that dies in
     * between leaves a sidecar that still owns those files (the next run deletes them) and that the
     * loader refuses.
     */
    interrupted: z.array(z.object({ id: z.string().min(1), file: z.string().min(1) }).strict()).optional(),
  })
  .strict();
export type ManagedManifest = z.infer<typeof ManagedManifestSchema>;

export class ManagedPortfolioError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ManagedPortfolioError";
  }
}

export function serializeManagedManifest(manifest: ManagedManifest): string {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/** The site's sidecar, or undefined when the site is not managed. A malformed sidecar throws. */
export async function readManagedManifest(siteDir: string): Promise<ManagedManifest | undefined> {
  const file = path.join(siteDir, MANAGED_FILE);
  let text: string;
  try {
    text = await readFile(file, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw new ManagedPortfolioError(`cannot read ${MANAGED_FILE}: ${(error as Error).message}`);
  }
  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch (error) {
    throw new ManagedPortfolioError(`${MANAGED_FILE} is not valid JSON: ${(error as Error).message}`);
  }
  const parsed = ManagedManifestSchema.safeParse(raw);
  if (!parsed.success) {
    throw new ManagedPortfolioError(`${MANAGED_FILE} invalid: ${parsed.error.issues.map((i) => `${i.path.join(".") || "(root)"}: ${i.message}`).join("; ")}`);
  }
  return parsed.data;
}

const WHERE_TO_EDIT = "it is GENERATED from BoostChat — edit the portfolio in the BoostChat admin and publish, then run site:portfolio-sync (--force regenerates it from what is live); never edit it here";

async function regularFileBytes(file: string): Promise<Buffer | undefined> {
  try {
    if (!(await lstat(file)).isFile()) return undefined;
    return await readFile(file);
  } catch {
    return undefined;
  }
}

/**
 * Loader guard. For a managed site: every generated file must still be exactly what the generator
 * recorded, and every managed registry entry must still be the generated one. Returns the problems
 * (empty = intact, or the site is not managed). Site-owned files and registry entries are not looked at.
 */
export async function managedPortfolioProblems(siteDir: string, siteId: string): Promise<string[]> {
  let manifest: ManagedManifest | undefined;
  try {
    manifest = await readManagedManifest(siteDir);
  } catch (error) {
    return [`${siteId}/${(error as Error).message}`];
  }
  let adopted = false;
  try {
    adopted = await hasSourceMarker(siteDir);
  } catch (error) {
    return [`${siteId}/${(error as Error).message}`];
  }
  if (!manifest) {
    if (!adopted) return [];
    return [
      `${siteId}: the portfolio of this site is owned by BoostChat (${SOURCE_MARKER_FILE}) but this checkout holds no generated portfolio (${MANAGED_FILE} is missing) — its content files may be older than what is live. Run "pnpm site:portfolio-sync --site ${siteId} --host <hostname> --force" (or --generate-only) to regenerate them`,
    ];
  }
  const problems: string[] = [];
  if (manifest.interrupted !== undefined) problems.push(`${siteId}/${MANAGED_FILE} records an INTERRUPTED regeneration (revision ${manifest.source.revision}) — run "pnpm site:portfolio-sync --site ${siteId} --host <hostname> --force" to finish it`);
  if (manifest.source.siteId !== siteId) problems.push(`${siteId}/${MANAGED_FILE} was generated for site "${manifest.source.siteId}"`);

  for (const expected of MANAGED_CONTENT_PATHS) {
    if (!manifest.content.some((c) => c.path === expected)) problems.push(`${siteId}/${MANAGED_FILE} does not record ${expected}`);
  }
  for (const c of manifest.content) {
    const bytes = await regularFileBytes(path.join(siteDir, c.path));
    if (!bytes) problems.push(`${siteId}/${c.path} is missing: ${WHERE_TO_EDIT}`);
    else if (sha256(bytes) !== c.sha256) {
      problems.push(`${siteId}/${c.path} was modified by hand (sha256 ${sha256(bytes).slice(0, 12)}… ≠ generated ${c.sha256.slice(0, 12)}…, revision ${manifest.source.revision}): ${WHERE_TO_EDIT}`);
    }
  }

  let registryItems: unknown[] | undefined;
  try {
    const registry = JSON.parse(await readFile(path.join(siteDir, REGISTRY_PATH), "utf8")) as { items?: unknown };
    if (Array.isArray(registry.items)) registryItems = registry.items;
  } catch {
    registryItems = undefined;
  }
  if (!registryItems) problems.push(`${siteId}/${REGISTRY_PATH} cannot be read, so its generated entries cannot be checked`);
  for (const a of manifest.assets) {
    const bytes = await regularFileBytes(path.join(siteDir, "assets", a.file));
    if (!bytes) problems.push(`${siteId}/assets/${a.file} (portfolio image "${a.id}") is missing: ${WHERE_TO_EDIT}`);
    else if (sha256(bytes) !== a.sha256) problems.push(`${siteId}/assets/${a.file} (portfolio image "${a.id}") was replaced by hand: ${WHERE_TO_EDIT}`);
    if (!registryItems) continue;
    const entries = registryItems.filter((e) => typeof e === "object" && e !== null && (e as { id?: unknown }).id === a.id);
    const { sha256: _sha, size: _size, ...generated } = a;
    const same = entries.length === 1 && JSON.stringify(sorted(entries[0] as Record<string, unknown>)) === JSON.stringify(sorted(generated));
    if (!same) problems.push(`${siteId}/${REGISTRY_PATH} entry "${a.id}" is not the generated one (${entries.length === 0 ? "missing" : entries.length > 1 ? "duplicated" : "edited"}): ${WHERE_TO_EDIT}`);
  }
  return problems;
}

function sorted(o: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries(Object.keys(o).sort().map((k) => [k, o[k]]));
}
